### ISSUE TITLE
Can you give some examples about the settings of parameters

### ISSUE THREAD

**Issue by ccdsg** [iliailia/heaan-vs-fv-sage#1]
hi，I am doing some research on FV scheme. And I used "sine_test function" and "power_test function",but I can't found  correct parameters for the FV scheme. Can you give me some examples like "power_test(2, 2, 2, 2, 'FV', 2, 2, 2)",which can make the program run smoothly and get the result. Thanks a lot.

**Comment by iliailia** [comment]
Hi, the valid parameters can be taken from Tables 2-16 in https://eprint.iacr.org/2020/121.pdf. 
For example, if you want to compute the sine function with 8 slots using FV, go to Table 5 and find the row with 8 slots. This row contains slots, enc_delta and b arguments of the sine_test function. The bound argument, which defines the range of a polynomial approximation of the sine function, must be at most pi as written in the caption of the table. The params_index argument is defined by n (0 if n=2^11, 1 if n=2^12 etc, see the beginning of the sage script).
As a result, your call should look like

sin_test(
slots = 8,
bound = pi, // see the caption of Table 5 
enc_delta = 2^26, // see the row of Table 5 with 8 slots
scheme_type = 'FV',
params_index = 2, //since n=2^13,  see the row of Table 5 with 8 slots
rounds = 10, //the number of tests you want to perform
b = 46  // see the row of Table 5 with 8 slots
)
